name: Deploy Web1 to Oracle Cloud

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            echo "=== START DEPLOY WEB1 ==="
            cd /var/www/web1.com/public_html || exit 1

            if [ ! -d ".git" ]; then
              echo "Cloning repository for the first time..."
              git clone https://github.com/Mandr11/web1.git .
            else
              echo "Pulling latest changes..."
              git reset --hard
              git pull origin main
            fi

            sudo chown -R ubuntu:www-data /var/www/web1.com/public_html
            sudo chmod -R 755 /var/www/web1.com/public_html

            sudo systemctl reload nginx
            sudo systemctl restart php8.1-fpm

            echo "=== DEPLOY WEB1 SUCCESSFUL ==="
